const express=require('express')
const controller=require('../controller/phonecontroller')
const router=express.Router()
router.post('/save', controller.save)
router.post('/first', controller.first)
router.get('/show',controller.show)
router.get('/showone',controller.showone)
router.get('/singleshow/:id',controller.singleShow)
router.delete('/delete',controller.delete)
router.post('/update',controller.update)
router.post('/updatepls',controller.updatename)
router.post('/complete',controller.complete)
router.delete('/deletion',controller.deletion)
router.delete('/deleteone',controller.deleteone)
router.post('/replc',controller.replc)
router.post('/reone',controller.reone)
router.delete('/remove',controller.remove)
router.post('/updateid',controller.updateid)
router.post('/many',controller.many)
module.exports=router
